/**
 *
 * Please note:
 * This class was auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package uk.gov.justice.digital.hmpps.prisonertonomisupdate.prisonperson.dpsmodel

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Physical Attributes
 *
 * @param height
 * @param weight
 * @param hair
 * @param facialHair
 * @param face
 * @param build
 * @param leftEyeColour
 * @param rightEyeColour
 */

data class PhysicalAttributesDto(

  @field:JsonProperty("height")
  val height: ValueWithMetadataInteger? = null,

  @field:JsonProperty("weight")
  val weight: ValueWithMetadataInteger? = null,

  @field:JsonProperty("hair")
  val hair: ReferenceDataCodeDto? = null,

  @field:JsonProperty("facialHair")
  val facialHair: ReferenceDataCodeDto? = null,

  @field:JsonProperty("face")
  val face: ReferenceDataCodeDto? = null,

  @field:JsonProperty("build")
  val build: ReferenceDataCodeDto? = null,

  @field:JsonProperty("leftEyeColour")
  val leftEyeColour: ReferenceDataCodeDto? = null,

  @field:JsonProperty("rightEyeColour")
  val rightEyeColour: ReferenceDataCodeDto? = null,

)
