/**
 *
 * Please note:
 * This class was auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package uk.gov.justice.digital.hmpps.prisonertonomisupdate.prisonperson.dpsmodel

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Prison Person
 *
 * @param prisonerNumber Prisoner Number
 * @param physicalAttributes
 */

data class PrisonPersonDto(

  /* Prisoner Number */
  @field:JsonProperty("prisonerNumber")
  val prisonerNumber: kotlin.String,

  @field:JsonProperty("physicalAttributes")
  val physicalAttributes: PhysicalAttributesDto,

)
