/**
 *
 * Please note:
 * This class was auto generated by OpenAPI Generator (https://openapi-generator.tech).
 *
 */

@file:Suppress(
  "ArrayInDataClass",
  "EnumEntryName",
  "RemoveRedundantQualifierName",
  "UnusedImport",
)

package uk.gov.justice.digital.hmpps.prisonertonomisupdate.prisonperson.dpsmodel

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Reference Data Code
 *
 * @param id Id
 * @param domain Short code for the reference data code
 * @param code Short code for reference data code
 * @param description Description of the reference data code
 * @param listSequence The sequence number of the reference data code. Used for ordering reference data correctly in lists and dropdowns. 0 is default order by description.
 * @param isActive Indicates that the reference data code is active and can be used. Inactive reference data codes are not returned by default in the API
 * @param createdAt The date and time the reference data code was created
 * @param createdBy The username of the user who created the reference data code
 * @param lastModifiedAt The date and time the reference data code was last modified
 * @param lastModifiedBy The username of the user who last modified the reference data code
 * @param deactivatedAt The date and time the reference data code was deactivated
 * @param deactivatedBy The username of the user who deactivated the reference data code
 */

data class ReferenceDataCodeDto(

  /* Id */
  @field:JsonProperty("id")
  val id: kotlin.String,

  /* Short code for the reference data code */
  @field:JsonProperty("domain")
  val domain: kotlin.String,

  /* Short code for reference data code */
  @field:JsonProperty("code")
  val code: kotlin.String,

  /* Description of the reference data code */
  @field:JsonProperty("description")
  val description: kotlin.String,

  /* The sequence number of the reference data code. Used for ordering reference data correctly in lists and dropdowns. 0 is default order by description. */
  @field:JsonProperty("listSequence")
  val listSequence: kotlin.Int,

  /* Indicates that the reference data code is active and can be used. Inactive reference data codes are not returned by default in the API */
  @field:JsonProperty("isActive")
  val isActive: kotlin.Boolean,

  /* The date and time the reference data code was created */
  @field:JsonProperty("createdAt")
  val createdAt: kotlin.String,

  /* The username of the user who created the reference data code */
  @field:JsonProperty("createdBy")
  val createdBy: kotlin.String,

  /* The date and time the reference data code was last modified */
  @field:JsonProperty("lastModifiedAt")
  val lastModifiedAt: kotlin.String? = null,

  /* The username of the user who last modified the reference data code */
  @field:JsonProperty("lastModifiedBy")
  val lastModifiedBy: kotlin.String? = null,

  /* The date and time the reference data code was deactivated */
  @field:JsonProperty("deactivatedAt")
  val deactivatedAt: kotlin.String? = null,

  /* The username of the user who deactivated the reference data code */
  @field:JsonProperty("deactivatedBy")
  val deactivatedBy: kotlin.String? = null,

)
