package uk.gov.justice.digital.hmpps.prisonertonomisupdate.locations

/**
 * Copied from hmpps-locations-inside-prison-api, used to lookup the ResidentialAttributeType from the ResidentialAttributeValue.
 */

enum class ResidentialAttributeType(
  val description: String,
) {
  USED_FOR("Used for"),
  LOCATION_ATTRIBUTE("Location attribute"),
  SANITATION_FITTINGS("Sanitation and fittings"),
  NON_ASSOCIATIONS("Non-associations"),
  SECURITY("Supervision and Security"),
}

enum class ResidentialAttributeValue(
  val type: ResidentialAttributeType,
  val description: String,
) {
  ANTI_BARRICADE_DOOR(ResidentialAttributeType.SANITATION_FITTINGS, "Anti Barricade Door"),
  AUDITABLE_CELL_BELL(ResidentialAttributeType.SANITATION_FITTINGS, "Auditable Cell Bell"),
  FIXED_BED(ResidentialAttributeType.SANITATION_FITTINGS, "Fixed Bed"),
  METAL_DOOR(ResidentialAttributeType.SANITATION_FITTINGS, "Metal Door"),
  MOVABLE_BED(ResidentialAttributeType.SANITATION_FITTINGS, "Movable Bed"),
  PRIVACY_CURTAIN(ResidentialAttributeType.SANITATION_FITTINGS, "Privacy Curtain"),
  PRIVACY_SCREEN(ResidentialAttributeType.SANITATION_FITTINGS, "Privacy Screen"),
  STANDARD_CELL_BELL(ResidentialAttributeType.SANITATION_FITTINGS, "Standard Cell Bell"),
  SEPARATE_TOILET(ResidentialAttributeType.SANITATION_FITTINGS, "Separate Toilet"),
  WOODEN_DOOR(ResidentialAttributeType.SANITATION_FITTINGS, "Wooden Door"),

  CAT_A_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Cat A Cell"),
  DOUBLE_OCCUPANCY(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Double Occupancy"),
  E_LIST_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "E List Cell"),
  GATED_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Gated Cell"),
  LISTENER_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Listener Cell"),
  LOCATE_FLAT(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Locate Flat"),
  MULTIPLE_OCCUPANCY(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Multiple Occupancy"),
  NON_SMOKER_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Non Smoker Cell"),
  OBSERVATION_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Observation Cell"),
  SAFE_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Safe Cell"),
  SINGLE_OCCUPANCY(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Single Occupancy"),
  SPECIAL_CELL(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Special Cell"),
  WHEELCHAIR_ACCESS(ResidentialAttributeType.LOCATION_ATTRIBUTE, "Wheelchair Access"),

  UNCONVICTED_JUVENILES(ResidentialAttributeType.USED_FOR, "Unconvicted Juveniles"),
  SENTENCED_JUVENILES(ResidentialAttributeType.USED_FOR, "Sentenced Juveniles"),
  UNCONVICTED_18_20(ResidentialAttributeType.USED_FOR, "Unconvicted 18 to 20 year olds"),
  SENTENCED_18_20(ResidentialAttributeType.USED_FOR, "Sentenced 18 to 20 year olds"),
  UNCONVICTED_ADULTS(ResidentialAttributeType.USED_FOR, "Unconvicted Adults"),
  SENTENCED_ADULTS(ResidentialAttributeType.USED_FOR, "Sentenced Adults"),
  VULNERABLE_PRISONER_UNIT(ResidentialAttributeType.USED_FOR, "Vulnerable Prisoner Unit"),
  SPECIAL_UNIT(ResidentialAttributeType.USED_FOR, "Special Unit"),
  RESETTLEMENT_HOSTEL(ResidentialAttributeType.USED_FOR, "Resettlement Hostel"),
  HEALTHCARE_CENTRE(ResidentialAttributeType.USED_FOR, "Healthcare Centre"),
  NATIONAL_RESOURCE_HOSPITAL(ResidentialAttributeType.USED_FOR, "National Resource Hospital"),
  OTHER_SPECIFIED(ResidentialAttributeType.USED_FOR, "Other (Please Specify)"),
  REMAND_CENTRE(ResidentialAttributeType.USED_FOR, "Remand Centre"),
  LOCAL_PRISON(ResidentialAttributeType.USED_FOR, "Local Prison"),
  CLOSED_PRISON(ResidentialAttributeType.USED_FOR, "Closed Prison"),
  OPEN_TRAINING(ResidentialAttributeType.USED_FOR, "Open Training"),
  HOSTEL(ResidentialAttributeType.USED_FOR, "Hostel"),
  CLOSED_YOUNG_OFFENDER(ResidentialAttributeType.USED_FOR, "Closed Young Offender Institute"),
  OPEN_YOUNG_OFFENDER(ResidentialAttributeType.USED_FOR, "Open Young Offender Institute"),
  REMAND_UNDER_18(ResidentialAttributeType.USED_FOR, "Remand Institute for Under 18s"),
  SENTENCED_UNDER_18(ResidentialAttributeType.USED_FOR, "Institution for Sentenced Under 18s"),
  ECL_COMPONENT(ResidentialAttributeType.USED_FOR, "ECL Component Code"),
  ADDITIONAL_SPECIAL_UNIT(ResidentialAttributeType.USED_FOR, "Additional Special Unit"),
  SECOND_CLOSED_TRAINER(ResidentialAttributeType.USED_FOR, "Second Closed Trainer/Single LIDS Site"),
  IMMIGRATION_DETAINEES(ResidentialAttributeType.USED_FOR, "Immigration Detainees"),

  CELL(ResidentialAttributeType.NON_ASSOCIATIONS, "Do Not Locate in Same Cell"),
  LANDING(ResidentialAttributeType.NON_ASSOCIATIONS, "Do Not Locate on Same Landing"),
  WING(ResidentialAttributeType.NON_ASSOCIATIONS, "Do Not Locate on Same Wing"),

  CAT_A(ResidentialAttributeType.SECURITY, "Cat A"),
  CAT_A_EX(ResidentialAttributeType.SECURITY, "Cat A Ex"),
  CAT_A_HI(ResidentialAttributeType.SECURITY, "Cat A Hi"),
  CAT_B(ResidentialAttributeType.SECURITY, "Cat B"),
  CAT_C(ResidentialAttributeType.SECURITY, "Cat C"),
  CAT_D(ResidentialAttributeType.SECURITY, "Cat D"),
  ELIGIBLE(ResidentialAttributeType.SECURITY, "Eligible"),
  PAROLE_GRANTED(ResidentialAttributeType.SECURITY, "Parole Granted"),
  INELIGIBLE(ResidentialAttributeType.SECURITY, "Ineligible"),
  YOI_CLOSED(ResidentialAttributeType.SECURITY, "YOI Closed"),
  YOI_OPEN(ResidentialAttributeType.SECURITY, "YOI Open"),
  YOI_RESTRICTED(ResidentialAttributeType.SECURITY, "YOI Restricted"),
  YOI_SHORT_SENTENCE(ResidentialAttributeType.SECURITY, "YOI Short Sentence"),
  YOI_LONG_TERM_CLOSED(ResidentialAttributeType.SECURITY, "YOI Long-Term Closed"),
  UNCLASSIFIED(ResidentialAttributeType.SECURITY, "Un-classified"),
  UNCATEGORISED_SENTENCED_MALE(ResidentialAttributeType.SECURITY, "Un-categorised Sentenced Male"),
  LOW(ResidentialAttributeType.SECURITY, "Low"),
  MEDIUM(ResidentialAttributeType.SECURITY, "Medium"),
  HIGH(ResidentialAttributeType.SECURITY, "High"),
  NOT_APPLICABLE(ResidentialAttributeType.SECURITY, "Not Applicable"),
  PROV_A(ResidentialAttributeType.SECURITY, "Prov A"),
  PENDING(ResidentialAttributeType.SECURITY, "Pending"),
  REF_REVIEW(ResidentialAttributeType.SECURITY, "Ref / Review - Date set for Review"),
  REFUSED_NO_REVIEW(ResidentialAttributeType.SECURITY, "Refused - No Review possible"),
  STANDARD(ResidentialAttributeType.SECURITY, "Standard"),
  FEMALE_RESTRICTED(ResidentialAttributeType.SECURITY, "Female Restricted"),
  FEMALE_CLOSED(ResidentialAttributeType.SECURITY, "Female Closed"),
  FEMALE_SEMI(ResidentialAttributeType.SECURITY, "Female Semi"),
  FEMALE_OPEN(ResidentialAttributeType.SECURITY, "Female Open"),
  UN_SENTENCED(ResidentialAttributeType.SECURITY, "Un-sentenced"),
  YES(ResidentialAttributeType.SECURITY, "Yes"),
  NO(ResidentialAttributeType.SECURITY, "No"),
}
