apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-activities-tidy-mappings
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.activitiesTidyMappingsSchedule }}"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      suspend: "{{ .Values.cron.activitiesTidyMappingsSuspend }}"
      template:
        spec:
          containers:
            - name: activities-tidy-mappings
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XDELETE http://hmpps-prisoner-to-nomis-update/activities/mappings/unknown-mappings
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
