apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-activities-purge-dlq
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "9-59/10 * * * *"
  suspend: {{ .Values.cron.activitiesPurgeDlqSuspend }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: activities-purge-dlq
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              volumeMounts:
                - name: hmpps-auth-token-requests
                  mountPath: /bin/hmpps-auth-token-requests.sh
                  readOnly: true
                  subPath: hmpps-auth-token-requests.sh
              args:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash
                  set -eu

                  source hmpps-auth-token-requests.sh

                  AUTH_BASE_URL="{{ index .Values "generic-service" "env" "API_BASE_URL_HMPPS_AUTH" }}"
                  QUEUE_NAME="{{ .Values.cron.activitiesPurgeDlqQueueName }}"

                  purge_queue() {
                    local token=$1
                    local queue_name=$2
                    curl --retry 2 -XPUT "http://hmpps-prisoner-to-nomis-update/queue-admin/purge-queue/$queue_name" \
                      -H "Authorization: Bearer $token"
                  }

                  # Main execution
                  TOKEN=$(get_auth_token "$AUTH_BASE_URL" "$CRONJOB_CLIENT_ID" "$CRONJOB_CLIENT_SECRET")
                  echo "Access token retrieved from HMPPS Auth"

                  purge_queue "$TOKEN" "$QUEUE_NAME"
                  echo "Queue purge completed successfully"
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              envFrom:
                - secretRef:
                    name: hmpps-prisoner-to-nomis-update
          restartPolicy: Never
          volumes:
            - name: hmpps-auth-token-requests
              configMap:
                name: hmpps-auth-token-requests-script
                defaultMode: 0755
