apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-queue-housekeeping
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "*/10 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: housekeeping
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              volumeMounts:
                - name: hmpps-auth-token-requests
                  mountPath: /bin/hmpps-auth-token-requests.sh
                  readOnly: true
                  subPath: hmpps-auth-token-requests.sh
              args:
                - /bin/sh
                - -c
                - |
                  #!/bin/bash
                  set -eu

                  . /bin/hmpps-auth-token-requests.sh

                  AUTH_BASE_URL="{{ index .Values "generic-service" "env" "API_BASE_URL_HMPPS_AUTH" }}"

                  retry_all_dlqs() {
                    local token=$1

                    response=$(curl -s -w "\n%{http_code}" --retry 2 -XPUT http://hmpps-prisoner-to-nomis-update/queue-admin/retry-all-dlqs \
                      -H "Authorization: Bearer $token")

                    echo $(parse_curl_response "$response")
                  }

                  # Main execution
                  TOKEN=$(get_auth_token "$AUTH_BASE_URL" "$CRONJOB_CLIENT_ID" "$CRONJOB_CLIENT_SECRET")
                  echo "Access token retrieved from HMPPS Auth"

                  retry_all_dlqs "$TOKEN"
                  echo "DLQ retry completed successfully"
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
              envFrom:
                - secretRef:
                    name: hmpps-prisoner-to-nomis-update
          restartPolicy: Never
          volumes:
            - name: hmpps-auth-token-requests
              configMap:
                name: hmpps-auth-token-requests-script
                defaultMode: 0755
