apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-report-prisonperson
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "30 5 * * *"
  suspend: {{ .Values.cron.prisonPersonReconsSuspend }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
            - name: report-prisonperson
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --retry 2 -XPUT http://hmpps-prisoner-to-nomis-update/prisonperson/reports/reconciliation
              securityContext:
                capabilities:
                  drop:
                  - ALL
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                seccompProfile:
                  type: RuntimeDefault
          restartPolicy: Never
