apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "app.fullname" . }}-report-allocationsnew
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.allocationReconReportScheduleNew }}"
  suspend: {{ .Values.cron.allocationsnew.suspend }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      # Tidy up all jobs after 4 days
      ttlSecondsAfterFinished: 345600
      template:
        spec:
          containers:
          - name: {{ include "generic-service.name" . }}
            env:
            - name: BATCH_ENABLED
              value: "true"
            - name: BATCH_TYPE
              value: ALLOCATION_RECON
            securityContext:
            {{- toYaml .Values.securityContext | nindent 14 }}
            image: "{{ index .Values "generic-service" "image" "repository" }}:{{ index .Values "generic-service" "image" "tag" | default .Chart.AppVersion }}"
            imagePullPolicy: {{ index .Values "generic-service" "image" "pullPolicy" }}
            ports:
              - name: http
                containerPort: {{ index .Values "generic-service" "image" "port" }}
                protocol: TCP
              {{- if not (eq (toString (index .Values "generic-service" "custommetrics" "metricsPort")) "http") }}
              - name: metrics
                containerPort: {{ .Values.custommetrics.metricsPort }}
                protocol: TCP
              {{- end }}
            resources:
            {{- toYaml .Values.resources | nindent 14 }}
            {{- include "deployment.envs" .Values | nindent 10 }}
            {{- with .Values.envFrom }}
            envFrom:
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .Values.volumeMounts }}
            volumeMounts:
            {{- toYaml . | nindent 12 }}
            {{- end }}
