package uk.gov.justice.digital.hmpps.prisonertonomisupdate.incidents

import uk.gov.justice.digital.hmpps.prisonertonomisupdate.incidents.model.PrisonerInvolvement.Outcome
import uk.gov.justice.digital.hmpps.prisonertonomisupdate.incidents.model.PrisonerInvolvement.PrisonerRole
import uk.gov.justice.digital.hmpps.prisonertonomisupdate.incidents.model.ReportWithDetails.Status
import uk.gov.justice.digital.hmpps.prisonertonomisupdate.incidents.model.ReportWithDetails.Type
import uk.gov.justice.digital.hmpps.prisonertonomisupdate.incidents.model.StaffInvolvement.StaffRole
import uk.gov.justice.digital.hmpps.prisonertonomisupdate.incidents.model.History.Type as HistoryType

internal fun Type.mapDps(): String = when (this) {
  Type.ABSCOND_1 -> "ABSCOND"
  Type.ASSAULT_1 -> "ASSAULT"
  Type.ASSAULT_2 -> "ASSAULTS"
  Type.ASSAULT_3 -> "ASSAULTS1"
  Type.ASSAULT_4 -> "ASSAULTS2"
  Type.ASSAULT_5 -> "ASSAULTS3"
  Type.ATTEMPTED_ESCAPE_FROM_PRISON_1 -> "ATT_ESCAPE"
  Type.ATTEMPTED_ESCAPE_FROM_ESCORT_1 -> "ATT_ESC_E"
  Type.BARRICADE_1 -> "BARRICADE"
  Type.BOMB_1 -> "BOMB"
  Type.BC_DISRUPT_3RD_PTY_1 -> "DIS_3RD_PTY"
  Type.BC_FUEL_SHORTAGE_1 -> "FUELSHORTAGE"
  Type.BC_LOSS_ACCESS_EGRESS_1 -> "LOSS_EGRESS"
  Type.BC_LOSS_COMMS_1 -> "LOSS_COMMS"
  Type.BC_LOSS_UTILS_1 -> "LOSS_UTILS"
  Type.BC_SERV_WEATHER_1 -> "SERV_WEATHER"
  Type.BC_STAFF_SHORTAGES_1 -> "STF_SHORTAGE"
  Type.BC_WIDESPREAD_ILLNESS_1 -> "WSPR_ILLNESS"
  Type.BREACH_OF_SECURITY_1 -> "BREACH"
  Type.CLOSE_DOWN_SEARCH_1 -> "CLOSE_DOWN"
  Type.CONCERTED_INDISCIPLINE_1 -> "CON_INDISC"
  Type.DAMAGE_1 -> "DAMAGE"
  Type.DEATH_PRISONER_1 -> "DEATH"
  Type.DEATH_OTHER_1 -> "DEATH_NI"
  Type.DIRTY_PROTEST_1 -> "DIRTYPROTEST"
  Type.DISORDER_1 -> "DISORDER"
  Type.DISORDER_2 -> "DISORDER1"
  Type.DRONE_SIGHTING_1 -> "DRONE"
  Type.DRONE_SIGHTING_2 -> "DRONE1"
  Type.DRONE_SIGHTING_3 -> "DRONE2"
  Type.DRUGS_1 -> "DRUGS"
  Type.ESCAPE_FROM_PRISON_1 -> "ESCAPE_EST"
  Type.ESCAPE_FROM_ESCORT_1 -> "ESCAPE_ESC"
  Type.FIND_1 -> "FINDS"
  Type.FIND_2 -> "FIND"
  Type.FIND_3 -> "FIND1"
  Type.FIND_4 -> "FIND0322"
  Type.FIND_5 -> "FINDS1"
  Type.FIND_6 -> "FIND0422"
  Type.FIRE_1 -> "FIRE"
  Type.FIREARM_1 -> "FIREARM_ETC"
  Type.FOOD_REFUSAL_1 -> "FOOD_REF"
  Type.HOSTAGE_1 -> "HOSTAGE"
  Type.INCIDENT_AT_HEIGHT_1 -> "ROOF_CLIMB"
  Type.KEY_OR_LOCK_1 -> "KEY_LOCK"
  Type.KEY_OR_LOCK_2 -> "KEY_LOCKNEW"
  Type.MISCELLANEOUS_1 -> "MISC"
  Type.MOBILE_PHONE_1 -> "MOBILES"
  Type.RADIO_COMPROMISE_1 -> "RADIO_COMP"
  Type.RELEASE_IN_ERROR_1 -> "REL_ERROR"
  Type.SELF_HARM_1 -> "SELF_HARM"
  Type.TEMPORARY_RELEASE_FAILURE_1 -> "TRF"
  Type.TEMPORARY_RELEASE_FAILURE_2 -> "TRF1"
  Type.TEMPORARY_RELEASE_FAILURE_3 -> "TRF2"
  Type.TEMPORARY_RELEASE_FAILURE_4 -> "TRF3"
  Type.TOOL_LOSS_1 -> "TOOL_LOSS"
}

// This is a duplicate mapping of above. In incident reporting it is one enum, but gets converted into two different
// ones when imported from the json :shrug:
internal fun HistoryType.mapDps(): String = when (this) {
  HistoryType.ABSCOND_1 -> "ABSCOND"
  HistoryType.ASSAULT_1 -> "ASSAULT"
  HistoryType.ASSAULT_2 -> "ASSAULTS"
  HistoryType.ASSAULT_3 -> "ASSAULTS1"
  HistoryType.ASSAULT_4 -> "ASSAULTS2"
  HistoryType.ASSAULT_5 -> "ASSAULTS3"
  HistoryType.ATTEMPTED_ESCAPE_FROM_PRISON_1 -> "ATT_ESCAPE"
  HistoryType.ATTEMPTED_ESCAPE_FROM_ESCORT_1 -> "ATT_ESC_E"
  HistoryType.BARRICADE_1 -> "BARRICADE"
  HistoryType.BC_DISRUPT_3RD_PTY_1 -> "DIS_3RD_PTY"
  HistoryType.BC_FUEL_SHORTAGE_1 -> "FUELSHORTAGE"
  HistoryType.BC_LOSS_ACCESS_EGRESS_1 -> "LOSS_EGRESS"
  HistoryType.BC_LOSS_COMMS_1 -> "LOSS_COMMS"
  HistoryType.BC_LOSS_UTILS_1 -> "LOSS_UTILS"
  HistoryType.BC_SERV_WEATHER_1 -> "SERV_WEATHER"
  HistoryType.BC_STAFF_SHORTAGES_1 -> "STF_SHORTAGE"
  HistoryType.BC_WIDESPREAD_ILLNESS_1 -> "WSPR_ILLNESS"
  HistoryType.BOMB_1 -> "BOMB"
  HistoryType.BREACH_OF_SECURITY_1 -> "BREACH"
  HistoryType.CLOSE_DOWN_SEARCH_1 -> "CLOSE_DOWN"
  HistoryType.CONCERTED_INDISCIPLINE_1 -> "CON_INDISC"
  HistoryType.DAMAGE_1 -> "DAMAGE"
  HistoryType.DEATH_PRISONER_1 -> "DEATH"
  HistoryType.DEATH_OTHER_1 -> "DEATH_NI"
  HistoryType.DIRTY_PROTEST_1 -> "DIRTYPROTEST"
  HistoryType.DISORDER_1 -> "DISORDER"
  HistoryType.DISORDER_2 -> "DISORDER1"
  HistoryType.DRONE_SIGHTING_1 -> "DRONE"
  HistoryType.DRONE_SIGHTING_2 -> "DRONE1"
  HistoryType.DRONE_SIGHTING_3 -> "DRONE2"
  HistoryType.DRUGS_1 -> "DRUGS"
  HistoryType.ESCAPE_FROM_PRISON_1 -> "ESCAPE_EST"
  HistoryType.ESCAPE_FROM_ESCORT_1 -> "ESCAPE_ESC"
  HistoryType.FIND_1 -> "FINDS"
  HistoryType.FIND_2 -> "FIND"
  HistoryType.FIND_3 -> "FIND1"
  HistoryType.FIND_4 -> "FIND0322"
  HistoryType.FIND_5 -> "FINDS1"
  HistoryType.FIND_6 -> "FIND0422"
  HistoryType.FIRE_1 -> "FIRE"
  HistoryType.FIREARM_1 -> "FIREARM_ETC"
  HistoryType.FOOD_REFUSAL_1 -> "FOOD_REF"
  HistoryType.HOSTAGE_1 -> "HOSTAGE"
  HistoryType.INCIDENT_AT_HEIGHT_1 -> "ROOF_CLIMB"
  HistoryType.KEY_OR_LOCK_1 -> "KEY_LOCK"
  HistoryType.KEY_OR_LOCK_2 -> "KEY_LOCKNEW"
  HistoryType.MISCELLANEOUS_1 -> "MISC"
  HistoryType.MOBILE_PHONE_1 -> "MOBILES"
  HistoryType.RADIO_COMPROMISE_1 -> "RADIO_COMP"
  HistoryType.RELEASE_IN_ERROR_1 -> "REL_ERROR"
  HistoryType.SELF_HARM_1 -> "SELF_HARM"
  HistoryType.TEMPORARY_RELEASE_FAILURE_1 -> "TRF"
  HistoryType.TEMPORARY_RELEASE_FAILURE_2 -> "TRF1"
  HistoryType.TEMPORARY_RELEASE_FAILURE_3 -> "TRF2"
  HistoryType.TEMPORARY_RELEASE_FAILURE_4 -> "TRF3"
  HistoryType.TOOL_LOSS_1 -> "TOOL_LOSS"
}

internal fun Status.mapDps(): String = when (this) {
  Status.DRAFT -> throw IncidentStatusIgnoredException(this)
  Status.AWAITING_REVIEW -> "AWAN"
  Status.ON_HOLD -> "INAN"
  Status.NEEDS_UPDATING -> "INREQ"
  Status.UPDATED -> "INAME"
  Status.CLOSED -> "CLOSE"
  Status.DUPLICATE, Status.NOT_REPORTABLE -> "DUP"
  Status.REOPENED, Status.WAS_CLOSED -> throw IncidentStatusIgnoredException(this)
}

internal fun PrisonerRole.mapDps(): String = when (this) {
  PrisonerRole.ABSCONDER -> "ABS"
  PrisonerRole.ACTIVE_INVOLVEMENT -> "ACTINV"
  PrisonerRole.ASSAILANT -> "ASSIAL"
  PrisonerRole.ASSISTED_STAFF -> "ASSIST"
  PrisonerRole.DECEASED -> "DEC"
  PrisonerRole.ESCAPE -> "ESC"
  PrisonerRole.FIGHTER -> "FIGHT"
  PrisonerRole.HOSTAGE -> "HOST"
  PrisonerRole.IMPEDED_STAFF -> "IMPED"
  PrisonerRole.IN_POSSESSION -> "INPOSS"
  PrisonerRole.INTENDED_RECIPIENT -> "INREC"
  PrisonerRole.LICENSE_FAILURE -> "LICFAIL"
  PrisonerRole.PERPETRATOR -> "PERP"
  PrisonerRole.PRESENT_AT_SCENE -> "PRESENT"
  PrisonerRole.SUSPECTED_ASSAILANT -> "SUSASS"
  PrisonerRole.SUSPECTED_INVOLVED -> "SUSINV"
  PrisonerRole.TEMPORARY_RELEASE_FAILURE -> "TRF"
  PrisonerRole.VICTIM -> "VICT"
}

internal fun Outcome.mapDps(): String = when (this) {
  Outcome.ACCT -> "ACCT"
  Outcome.CHARGED_BY_POLICE -> "CBP"
  Outcome.CONVICTED -> "CON"
  Outcome.CORONER_INFORMED -> "CORIN"
  Outcome.DEATH -> "DEA"
  Outcome.FURTHER_CHARGES -> "FCHRG"
  Outcome.LOCAL_INVESTIGATION -> "ILOC"
  Outcome.NEXT_OF_KIN_INFORMED -> "NKI"
  Outcome.PLACED_ON_REPORT -> "POR"
  Outcome.POLICE_INVESTIGATION -> "IPOL"
  Outcome.REMAND -> "RMND"
  Outcome.SEEN_DUTY_GOV -> "DUTGOV"
  Outcome.SEEN_HEALTHCARE -> "HELTH"
  Outcome.SEEN_IMB -> "IMB"
  Outcome.SEEN_OUTSIDE_HOSP -> "OUTH"
  Outcome.TRANSFER -> "TRN"
  Outcome.TRIAL -> "TRL"
}

internal fun StaffRole.mapDps(): String = when (this) {
  StaffRole.ACTIVELY_INVOLVED -> "AI"
  StaffRole.AUTHORISING_OFFICER -> "AO"
  StaffRole.CR_HEAD -> "CRH"
  StaffRole.CR_LEFT_ARM -> "CRL"
  StaffRole.CR_LEGS -> "CRLG"
  StaffRole.CR_RIGHT_ARM -> "CRR"
  StaffRole.CR_SUPERVISOR -> "CRS"
  StaffRole.DECEASED -> "DEC"
  StaffRole.FIRST_ON_SCENE -> "FOS"
  StaffRole.HEALTHCARE -> "HEALTH"
  StaffRole.HOSTAGE -> "HOST"
  StaffRole.IN_POSSESSION -> "INPOS"
  StaffRole.NEGOTIATOR -> "NEG"
  StaffRole.PRESENT_AT_SCENE -> "PAS"
  StaffRole.SUSPECTED_INVOLVEMENT -> "SUSIN"
  StaffRole.VICTIM -> "VICT"
  StaffRole.WITNESS -> "WIT"
}
