name: Security trivy dependency check
on:
  workflow_dispatch:
  schedule:
    - cron: "25 4 * * MON-FRI" # Every weekday at 04:25 UTC
jobs:
  security-kotlin-trivy-check:
    name: Project security trivy dependency check
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_trivy.yml@0.2 # WORKFLOW_VERSION 
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SRE_SLACK_BOT_TOKEN }}
