name: Setup api matrix
on:
  workflow_call:
    secrets:
      GRADLE_CACHE_ENCRYPTION_KEY:
        required: false
    inputs:
      java-version:
        type: string
        required: false
        default: '25'
    outputs:
      matrix:
        value: ${{ jobs.create_matrix.outputs.task_output }}

permissions:
  contents: read
jobs:
  create_matrix:
    name: Create api matrix
    runs-on: ubuntu-latest
    outputs:
      task_output: ${{ steps.create_matrix.outputs.taskoutput }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: 'temurin'
          java-version: '${{ inputs.java-version }}'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-encryption-key: ${{ secrets.GRADLE_CACHE_ENCRYPTION_KEY }}
      - name: Create api matrix
        id: create_matrix
        shell: bash
        run: |
          TASKS=$(./gradlew tasks | awk '/- Write JSON/ {print $1}')
          echo "taskoutput=$(echo "$TASKS" | jq -cRn "{"project":[inputs]}")" >> $GITHUB_OUTPUT
